### ISSUE TITLE
Knobby Setup Site Issues

### ISSUE THREAD

**Issue by nullstalgia** [quadule/knobby#14]
Couldn't find a repo for it, so wanted to note some bugs I had.

1. WiFi Password field is missing, I always have to use "Other Network" to get the prompt.

![image](https://github.com/quadule/knobby/assets/20761757/a7a6e35a-76a9-46cc-8dd2-f09b830c2045)

2. Rarely will ask to install Knobby on already-flashed device until after opening Logs and hitting Reset Device.

3. Mesh network duplicates aren't suppressed. Pretty minor.
![image](https://github.com/quadule/knobby/assets/20761757/369afe30-e5f9-49e0-9656-d416929e1603)

**Comment by quadule** [comment]
Thanks for reporting these; I've pushed a few updates to address them:

1. Turns out the "password required" flag in the [improv-wifi](https://github.com/improv-wifi) serial protocol was flipped, but older versions of [esp-web-tools](https://github.com/esphome/esp-web-tools) didn't care and always showed the password field. I'm pinning the older version of esp-web-tools for now to fix this issue for users running older firmware.

2. I've seen this a couple times before — not sure if there's much I can do but I added a note to wake the device first before connecting.

3. This one was easy enough to fix; duplicate SSIDs should be skipped now.
