### ISSUE TITLE
Liked songs playlist missing from Playlists?

### ISSUE THREAD

**Issue by nullstalgia** [quadule/knobby#7]
Hi! Just wanted to say I love this project and assembled my own earlier today. (I'm surprised you don't have a Tindie or something set up, quite frankly.)

However, as someone who uses the Liked songs playlist (I know it has issues), that's the one thing I'm missing! I hope I'm just not missing something in the UI.

**Comment by quadule** [comment]
Hi, I'm glad to hear you're enjoying it! I do hope to get a Tindie shop up sometime.

You are right that there's currently no way to access liked songs. I haven't built any UI for browsing individual tracks yet, and was originally planning to do a larger refactor before attempting that.

Spotify has a separate API for getting saved tracks instead of representing them as a playlist, but I just noticed that they can also be played from a context_uri like `spotify:user:{user_id}:collection`. That should make it easy to add a virtual Liked Songs playlist to the beginning of the Playlists menu, so you could at least start playing and skip between songs from there. I think I can add that to the next release!

**Comment by nullstalgia** [comment]
Awesome! Also, I might throw in a PR soon since I think the Double-Tap in Genre menu is bugged (only switching between the first two `GenreSortModes`), but I've been having issues compiling...

I'll throw the errors at you in case you've seen them before:

> Error: Could not find one of 'package.json' manifest files in the package

![image](https://user-images.githubusercontent.com/20761757/191197524-49e446de-5d52-4242-8305-6f0dd4426710.png)

> Unable to determine what CMake generator to use. Please install or configure a preferred generator, or update settings.json, your Kit configuration or PATH variable.

![image](https://user-images.githubusercontent.com/20761757/191197604-5b483da2-3b22-4538-81b5-e40d5d7cb88d.png)

Before it was saying "Bad cmake executable" until I installed it from the website, and now I'm getting those errors. PlatformIO is great but I find it annoying sometimes 😅

**Comment by nullstalgia** [comment]
Ahh, seems you only added the new options in a recent commit, gotcha.

And I was able to successfully compile on my Linux machine. Didn't try uploading via Serial, but the OTA with the .bin worked for me.

**Comment by quadule** [comment]
Just released a [new version](https://github.com/quadule/knobby/releases/tag/2022.11.06) with this added; thanks again for the suggestion!

**Comment by nullstalgia** [comment]
Awesome!

But sadly, it's not working for me. When I select that playlist, Spotify just stops playing and the controls grey out on the Desktop.
![image](https://user-images.githubusercontent.com/20761757/209420393-406eee71-4540-433e-89dc-34d13a1be715.png)
